[package]
name = "automations"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures-util = "0.3.31"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"] }
zbus = "5.12.0"
